{
    "Target": {
        "EntitySet": "IncidentHistory",
        "Service": "/IncidentReporting/Services/PA49930U00.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/IncidentReporting/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/IncidentReporting/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}