{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "IncidentPhotos",
        "Service": "/IncidentReporting/Services/PA49930U00.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "imageType": "#Control:imageType/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/IncidentReporting/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/IncidentReporting/Actions/UpdateEntityFailureMessage.action"
}