{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/IncidentReporting/Pages/SafetyIncidents/SafetyIncidents_CreateIncidentHistory.page",
    "_Type": "Action.Type.Navigation"
}