{
    "ParentLink": {
        "Property": "incidentHistory",
        "Target": {
            "EntitySet": "SafetyIncidents",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/IncidentReporting/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/IncidentReporting/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "oldStatus_code": "#Control:oldStatus_code/#SelectedValue",
        "newStatus_code": "#Control:newStatus_code/#SelectedValue"
    },
    "Target": {
        "EntitySet": "IncidentHistory",
        "Service": "/IncidentReporting/Services/PA49930U00.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}